# Generated by Django 5.0.6 on 2024-06-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cab_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SharedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_link', models.CharField(max_length=100, unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('companion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_companion', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
