# Generated by Django 5.0.6 on 2024-06-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_cab_location_sharedride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
