# Generated by Django 5.0.6 on 2024-06-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rename_feedback_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rides.ride'),
        ),
    ]
